### ISSUE TITLE
很有趣的工作，想请问，对于统计不准该如何改善？

### ISSUE THREAD

**Issue by sanbuphy** [songrise/CLIP-Count#8]
![image](https://github.com/songrise/CLIP-Count/assets/96160062/a60d29cc-d6e0-497e-9bc4-50ab70be7a19)
注意到这张图，其实很多并不是红点，而是蓝色点，这个是不是代表置信度比较低？

**Comment by songrise** [comment]
是的，可以认为置信度较低。 训练的时候监督的密度点是在一个人为定义的物体中心，测试的时候有的不对称的物体可能不能很好的找到其中心。FSC-147数据集用于文本引导计数不是特别理想，还包含很多错误的样本。或许可以考虑改善训练数据集。

---

Q: a lot of dots are blue instead of red, does this indecate low fidelity,
A: it could be interpreted in this way. This could be attributed to the dot-annotation in FSC-147, which is expected to be perfectly located in the object centroid. In practice, the concept of "centroid" for non-assymetric object is not well-defined. I suggest further research focusing on annotating a dataset to better address this issue.

**Comment by sanbuphy** [comment]
> 是的，可以认为置信度较低。 训练的时候监督的密度点是在一个人为定义的物体中心，测试的时候有的不对称的物体可能不能很好的找到其中心。FSC-147数据集用于文本引导计数不是特别理想，还包含很多错误的样本。或许可以考虑改善训练数据集。
> 
> Q: a lot of dots are blue instead of red, does this indecate low fidelity, A: it could be interpreted in this way. This could be attributed to the dot-annotation in FSC-147, which is expected to be perfectly located in the object centroid. In practice, the concept of "centroid" for non-assymetric object is not well-defined. I suggest further research focusing on annotating a dataset to better address this issue.

Thank you for your response. I believe that with a sufficiently large dataset, this model should be able to cover the vast majority of cases. This idea is great, and I anticipate even better results in larger models.
